/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class EmojiModel {
  imgSrc: Resource;

  constructor(imgSrc: Resource) {
    this.imgSrc = imgSrc;
  }
}

export const EmojiData = [
  new EmojiModel($rawfile('01.png')),
  new EmojiModel($rawfile('02.png')),
  new EmojiModel($rawfile('03.png')),
  new EmojiModel($rawfile('04.png')),
  new EmojiModel($rawfile('05.png')),
  new EmojiModel($rawfile('06.png')),
  new EmojiModel($rawfile('07.png')),
  new EmojiModel($rawfile('08.png')),
  new EmojiModel($rawfile('09.png')),
  new EmojiModel($rawfile('10.png')),
  new EmojiModel($rawfile('11.png')),
  new EmojiModel($rawfile('12.png')),
  new EmojiModel($rawfile('13.png')),
  new EmojiModel($rawfile('14.png')),
  new EmojiModel($rawfile('15.png')),
  new EmojiModel($rawfile('16.png')),
  new EmojiModel($rawfile('17.png')),
  new EmojiModel($rawfile('18.png')),
  new EmojiModel($rawfile('19.png')),
  new EmojiModel($rawfile('20.png')),
  new EmojiModel($rawfile('21.png')),
  new EmojiModel($rawfile('22.png')),
  new EmojiModel($rawfile('23.png')),
  new EmojiModel($rawfile('24.png')),
  new EmojiModel($rawfile('25.png')),
  new EmojiModel($rawfile('26.png')),
  new EmojiModel($rawfile('27.png')),
  new EmojiModel($rawfile('28.png')),
  new EmojiModel($rawfile('29.png')),
  new EmojiModel($rawfile('30.png')),
  new EmojiModel($rawfile('31.png')),
  new EmojiModel($rawfile('32.png')),
];